backend:
  name: git-gateway
  #name: test-repo
  branch: main

media_folder: "media"
collections:
  - label: "Homepage"
    name: "homepage"
    folder: "homepage"
    create: true
    fields:
      - { label: "Header",  name: "header", widget: "string" }